"""
DISCLAIMER: GENERATED BY AI
Live solar panel monitoring with three stacked plots:
    1. Voltage
    2. Current
    3. Cell temperature

This script combines:
- the live database polling / matplotlib animation from live_data.py
- the three-subplot layout from plot_csv.py

Change MODULE_NAME below to choose which solar module is plotted.
"""

from __future__ import annotations

import datetime as dt
import zoneinfo
from collections import deque
from typing import Optional, Sequence

import matplotlib
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

from tud_pv_monitoring.database import init, db_close


# -----------------------------------------------------------------------------
# User settings
# -----------------------------------------------------------------------------
MODULE_NAME = "My_solar_panel_1"
TIMEZONE = "Europe/Amsterdam"
POLL_INTERVAL_MS = 1_000          # Query the database every 3 seconds
WINDOW_DURATION = dt.timedelta(minutes=1)
MAX_POINTS = 1_000                # Prevent unlimited memory growth

# Database column names. These match the CSV columns used in plot_csv.py.
# If your database uses different names, change them here.
TIME_COL = "date_time"
VOLTAGE_COL = "v"
CURRENT_COL = "i"
TEMP_COL = "temperature_cell"
TABLE_NAME = "pv_point"
MODULE_COL = "module_name"


# -----------------------------------------------------------------------------
# Database helpers
# -----------------------------------------------------------------------------
def last_measurement(cur, module_name: str) -> Optional[tuple]:
    """
    Return the latest measurement for one module as:
        (date_time, voltage, current, temperature_cell)

    The old live_data.py selected every column with SELECT * and then used
    numeric indexes. This version selects only the needed columns by name,
    which is safer and easier to maintain.
    """
    query = f"""
        SELECT {TIME_COL}, {VOLTAGE_COL}, {CURRENT_COL}, {TEMP_COL}
        FROM {TABLE_NAME}
        WHERE {MODULE_COL} = %s
        ORDER BY {TIME_COL} DESC
        LIMIT 1
    """
    cur.execute(query, (module_name,))
    return cur.fetchone()


def to_local_datetime(value, timezone_name: str) -> dt.datetime:
    """Ensure timestamps are timezone-aware for correct matplotlib formatting."""
    timezone = zoneinfo.ZoneInfo(timezone_name)

    if isinstance(value, str):
        value = dt.datetime.fromisoformat(value)

    if value.tzinfo is None:
        return value.replace(tzinfo=timezone)

    return value.astimezone(timezone)


# -----------------------------------------------------------------------------
# Plot setup
# -----------------------------------------------------------------------------
matplotlib.set_loglevel("warning")

conn = None
mysql_conn = None
animation = None
last_seen_time = None

# Deques automatically discard old points after MAX_POINTS.
times = deque(maxlen=MAX_POINTS)
voltages = deque(maxlen=MAX_POINTS)
currents = deque(maxlen=MAX_POINTS)
temperatures = deque(maxlen=MAX_POINTS)

fig, axes = plt.subplots(
    3,
    1,
    figsize=(12, 8),
    sharex=True,
    constrained_layout=True,
)

voltage_line, = axes[0].plot([], [], marker="o", linewidth=1, markersize=3, label="Voltage")
current_line, = axes[1].plot([], [], marker="o", linewidth=1, markersize=3, label="Current")
temperature_line, = axes[2].plot([], [], marker="o", linewidth=1, markersize=3, label="Cell temperature")

plot_config = [
    (axes[0], voltage_line, "Voltage [V]"),
    (axes[1], current_line, "Current [A]"),
    (axes[2], temperature_line, "Cell temperature [°C]"),
]

for ax, line, ylabel in plot_config:
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper left")

axes[-1].set_xlabel("Time")
fig.suptitle(f"Live solar panel measurements: {MODULE_NAME}")

# Format x-axis as local clock time.
timezone = zoneinfo.ZoneInfo(TIMEZONE)
locator = mdates.AutoDateLocator()
formatter = mdates.DateFormatter("%H:%M:%S", tz=timezone)
axes[-1].xaxis.set_major_locator(locator)
axes[-1].xaxis.set_major_formatter(formatter)
fig.autofmt_xdate()


def update(_frame) -> Sequence:
    """Fetch the newest database row and update all three live plots."""
    global last_seen_time

    measurement = last_measurement(cur, MODULE_NAME)

    if measurement is None:
        print(f"No measurements found for module: {MODULE_NAME}")
        return voltage_line, current_line, temperature_line

    measurement_time, voltage, current, temperature = measurement
    measurement_time = to_local_datetime(measurement_time, TIMEZONE)

    # Avoid plotting the same database row repeatedly between new measurements.
    if measurement_time == last_seen_time:
        return voltage_line, current_line, temperature_line

    last_seen_time = measurement_time
    print(measurement)

    times.append(measurement_time)
    voltages.append(voltage)
    currents.append(current)
    temperatures.append(temperature)

    voltage_line.set_data(times, voltages)
    current_line.set_data(times, currents)
    temperature_line.set_data(times, temperatures)

    for ax in axes:
        ax.relim()
        ax.autoscale_view(scalex=False, scaley=True)

    # Show a scrolling time window once at least one point exists.
    if times:
        axes[-1].set_xlim(times[-1] - WINDOW_DURATION, times[-1])

    return voltage_line, current_line, temperature_line


def on_close(_event) -> None:
    """Close database connections when the matplotlib window is closed."""
    if conn is not None and mysql_conn is not None:
        db_close(conn, mysql_conn)


if __name__ == "__main__":
    conn, cur, mysql_conn, mysql_cur = init()
    fig.canvas.mpl_connect("close_event", on_close)

    animation = FuncAnimation(
        fig,
        update,
        interval=POLL_INTERVAL_MS,
        cache_frame_data=False,
    )

    try:
        plt.show()
    finally:
        # Also close connections if the program exits without a close_event.
        if conn is not None and mysql_conn is not None:
            db_close(conn, mysql_conn)
